[tool.poetry]
name = "veronica"
version = "13.6.2021"
description = ""
authors = ["shiddharth <hitblastofficial@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
async-timeout = "^3.0.1"
discord = "^1.0.1"
flask = "^1.1.2"
youtube-dl = "^2021.3.2"
PyNaCl = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
